### PR TITLE
Add overview of the component

### PR DESCRIPTION
**Pull request by ssxlulu**
pull request for #15

### CODE REVIEW

**Comment by avalon566** [comment]
@ssxlulu The flowchart is incorrect, the component only supports resharding data to new databases, not slice data resharding.

**Comment by ssxlulu** [comment]
ds_$ is the represent of mysql schema, this figure expresses migrating ds_1 schema  to another mysql instance, the same is the ds_3. It doesn't mean resharding.

**Comment by KomachiSion** [comment]
I think the picture should figure more detail of migrating steps. 

For example, first, the history data is select from old two instances and insert to new four instances and mark the position of binlogs. 
Then realtime data DML to new four instances by dump binlog. 
Finally, we switch the configuration of sharding-jdbc/sharding-proxy, make application connect to new four instances

Is it better?

**Comment by ssxlulu** [comment]
> @ssxlulu I got it, Your figure expresses one of the mirgrating situation. We can discuss which mirgrating situation we can support or we should support, The situation better match shardingsphere user. Then write into the doc and provide an example.

I just take a overlook at the project, and don't know others situations, so sorry. I think you are the man who know it best. So you can add the other situations.

**Comment by ssxlulu** [comment]
> I think the picture should figure more detail of migrating steps.
> 
> For example, first, the history data is select from old two instances and insert to new four instances and mark the position of binlogs.
> Then realtime data DML to new four instances by dump binlog.
> Finally, we switch the configuration of sharding-jdbc/sharding-proxy, make application connect to new four instances
> 
> Is it better?

Sorry, I didn't make it clearly.The figure expresses that situation: migrate two mysql schemas to another tow mysql schemas with the same name in another two mysql instance.
So, after scaling out, the storage is twice as large as before.

**Comment by avalon566** [comment]
@ssxlulu Do you mean respectively migrate shema_1 and schema_3 to other instance?

**Comment by ssxlulu** [comment]
> @ssxlulu Do you mean respectively migrate shema_1 and schema_3 to other instance?

Yes, It is what I mean.

**Comment by ssxlulu** [comment]
I have add some graphic sample to make the figure more readable.

**Pull request merged**
